version: '2'
services:
  hooktftp:
    image: spacklerind/hooktftp
    container_name: hooktftp
    ports:
      - "69:69/tcp"
      - "69:69/udp"
    restart: always
    volumes:
      - ./hooktftp:/etc/hooktftp
  dnsmasq:
    image: spacklerind/dnsmasq
    cap_add:
      - NET_ADMIN
    container_name: dnsmasq
    ports:
      - "67:67/tcp"
    restart: always
    network_mode: "host"
    volumes:
      - ./dnsmasq:/app/
  bushwood:
    image: spacklerind/bushwood
    container_name: bushwood
    ports:
      - "8080:8080/tcp"
    restart: always
    volumes:
      - ./bushwood:/app/caddyshack
    environment:
      - BAKERY_SERVER=http://10.1.1.2:8081
      - HTTP_PORT=8080
      - JWT_SECRET=raspberrypi
      - DB_PATH=/app/caddyshack/caddyshack.db
      - SPACKLER_SERVER=http://10.1.1.1:8585
      - LOOMIS_SERVER=http://10.1.1.1:8090
  bakery:
    image: spacklerind/bakery
    container_name: bakery
    ports:
      - "8081:8080/tcp"
      - "111:111"
      - "2049:2049"
      - "111:111/udp"
      - "2049:2049/udp"
    restart: always
    volumes:
      - ./bakery:/app/bakery
    environment:
      - BAKERY_ADDRESS=10.1.1.2
      - HTTP_PORT=8081
      - BUSHWOOD_SERVER=http://10.1.1.1:8080
      - BUSHWOOD_TOKEN=d42a152bff711f187479d8613ccb47925d82b21a
      - TEMPLATE_PATH=/go/src/bakery/fileTemplates
 spackler:
    image: spacklerind/spackler
    container_name: spackler
    ports:
      - "8585:8080/tcp"
    restart: always
    devices:
      - "/dev/ttyS0:/dev/ttyS0"
    environment:
      - BUSHWOOD_TOKEN=d42a152bff711f187479d8613ccb47925d82b21a
      - BUSHWOOD_SERVER=http://10.1.1.1:8080
      - SERIAL_DEVICE=/dev/ttyS0
  loomis:
    image: spacklerind/loomis
    container_name: loomis
    ports:
      - "8090:8080/tcp"
      - "8091:8081/tcp"
    restart: always
    volumes:
      - ./loomis:/app/loomis/config
      - /dev:/dev
    privileged: true
    environment:
      - DOCKER_HTT_PORT=8090
      - DOCKER_CONSOLES_PORT=8091
      - BUSHWOOD_TOKEN=d42a152bff711f187479d8613ccb47925d82b21a
      - BUSHWOOD_SERVER=http://10.1.1.1:8080
      - LOOMIS_ADDRESS=10.1.1.1
